export const bookIdLookup = new Map([
  ["GEN", "Genesis"],
  ["EXO", "Exodus"],
  ["LEV", "Leviticus"],
  ["NUM", "Numbers"],
  ["DEU", "Deuteronomy"],
  ["JOS", "Joshua"],
  ["JDG", "Judges"],
  ["RUT", "Ruth"],
  ["1SA", "I Samuel"],
  ["2SA", "II Samuel"],
  ["1KI", "I Kings"],
  ["2KI", "II Kings"],
  ["1CH", "I Chronicles"],
  ["2CH", "II Chronicles"],
  ["EZR", "Ezra"],
  ["NEH", "Nehemiah"],
  ["EST", "Esther"],
  ["JOB", "Job"],
  ["PSA", "Psalms"],
  ["PRO", "Proverbs"],
  ["ECC", "Ecclesiastes"],
  ["SNG", "Song of Solomon"],
  ["ISA", "Isaiah"],
  ["JER", "Jeremiah"],
  ["LAM", "Lamentations"],
  ["EZK", "Ezekiel"],
  ["DAN", "Daniel"],
  ["HOS", "Hosea"],
  ["JOL", "Joel"],
  ["AMO", "Amos"],
  ["OBA", "Obadiah"],
  ["JON", "Jonah"],
  ["MIC", "Micah"],
  ["NAM", "Nahum"],
  ["HAB", "Habakkuk"],
  ["ZEP", "Zephaniah"],
  ["HAG", "Haggai"],
  ["ZEC", "Zechariah"],
  ["MAL", "Malachi"],
  ["MAT", "Matthew"],
  ["MRK", "Mark"],
  ["LUK", "Luke"],
  ["JHN", "John"],
  ["ACT", "Acts"],
  ["ROM", "Romans"],
  ["1CO", "I Corinthians"],
  ["2CO", "II Corinthians"],
  ["GAL", "Galatians"],
  ["EPH", "Ephesians"],
  ["PHP", "Philippians"],
  ["COL", "Colossians"],
  ["1TH", "I Thessalonians"],
  ["2TH", "II Thessalonians"],
  ["1TI", "I Timothy"],
  ["2TI", "II Timothy"],
  ["TIT", "Titus"],
  ["PHM", "Philemon"],
  ["HEB", "Hebrews"],
  ["JAS", "James"],
  ["1PE", "I Peter"],
  ["2PE", "II Peter"],
  ["1JN", "I John"],
  ["2JN", "II John"],
  ["3JN", "III John"],
  ["JUD", "Jude"],
  ["REV", "Revelation of John"],
  ["TOB", "Tobit"],
  ["JDT", "Judith"],
  ["WIS", "Wisdom"],
  ["SIR", "Sirach"],
  ["BAR", "Baruch"],
  ["1MA", "I Maccabees"],
  ["2MA", "II Maccabees"],
  ["MAN", "Prayer of Manasses"],
  ["1ES", "I Esdras"],
  ["2ES", "II Esdras"],
  ["PS2", "Additional Psalm"],
  ["LAO", "Laodiceans"],
]);

export const bookGroups = [
  "Pentateuch",
  "History",
  "Poetry",
  "Major Prophets",
  "Minor Prophets",
  "Gospels",
  "Early Church",
  "Epistles",
  "Prophetic",
];

export const bookTestamentLookup = new Map([
  ["GEN", "Old Testament"],
  ["EXO", "Old Testament"],
  ["LEV", "Old Testament"],
  ["NUM", "Old Testament"],
  ["DEU", "Old Testament"],
  ["JOS", "Old Testament"],
  ["JDG", "Old Testament"],
  ["RUT", "Old Testament"],
  ["1SA", "Old Testament"],
  ["2SA", "Old Testament"],
  ["1KI", "Old Testament"],
  ["2KI", "Old Testament"],
  ["1CH", "Old Testament"],
  ["2CH", "Old Testament"],
  ["EZR", "Old Testament"],
  ["NEH", "Old Testament"],
  ["EST", "Old Testament"],
  ["JOB", "Old Testament"],
  ["PSA", "Old Testament"],
  ["PRO", "Old Testament"],
  ["ECC", "Old Testament"],
  ["SNG", "Old Testament"],
  ["ISA", "Old Testament"],
  ["JER", "Old Testament"],
  ["LAM", "Old Testament"],
  ["EZK", "Old Testament"],
  ["DAN", "Old Testament"],
  ["HOS", "Old Testament"],
  ["JOL", "Old Testament"],
  ["AMO", "Old Testament"],
  ["OBA", "Old Testament"],
  ["JON", "Old Testament"],
  ["MIC", "Old Testament"],
  ["NAM", "Old Testament"],
  ["HAB", "Old Testament"],
  ["ZEP", "Old Testament"],
  ["HAG", "Old Testament"],
  ["ZEC", "Old Testament"],
  ["MAL", "Old Testament"],
  ["MAT", "New Testament"],
  ["MRK", "New Testament"],
  ["LUK", "New Testament"],
  ["JHN", "New Testament"],
  ["ACT", "New Testament"],
  ["ROM", "New Testament"],
  ["1CO", "New Testament"],
  ["2CO", "New Testament"],
  ["GAL", "New Testament"],
  ["EPH", "New Testament"],
  ["PHP", "New Testament"],
  ["COL", "New Testament"],
  ["1TH", "New Testament"],
  ["2TH", "New Testament"],
  ["1TI", "New Testament"],
  ["2TI", "New Testament"],
  ["TIT", "New Testament"],
  ["PHM", "New Testament"],
  ["HEB", "New Testament"],
  ["JAS", "New Testament"],
  ["1PE", "New Testament"],
  ["2PE", "New Testament"],
  ["1JN", "New Testament"],
  ["2JN", "New Testament"],
  ["3JN", "New Testament"],
  ["JUD", "New Testament"],
  ["REV", "New Testament"],
  ["TOB", "Apocrypha"],
  ["JDT", "Apocrypha"],
  ["WIS", "Apocrypha"],
  ["SIR", "Apocrypha"],
  ["BAR", "Apocrypha"],
  ["1MA", "Apocrypha"],
  ["2MA", "Apocrypha"],
  ["MAN", "Apocrypha"],
  ["1ES", "Apocrypha"],
  ["2ES", "Apocrypha"],
]);

export const bookGroupLookup = new Map([
  ["GEN", "Pentateuch"],
  ["EXO", "Pentateuch"],
  ["LEV", "Pentateuch"],
  ["NUM", "Pentateuch"],
  ["DEU", "Pentateuch"],
  ["JOS", "History"],
  ["JDG", "History"],
  ["RUT", "History"],
  ["1SA", "History"],
  ["2SA", "History"],
  ["1KI", "History"],
  ["2KI", "History"],
  ["1CH", "History"],
  ["2CH", "History"],
  ["EZR", "History"],
  ["NEH", "History"],
  ["EST", "History"],
  ["JOB", "Poetry"],
  ["PSA", "Poetry"],
  ["PRO", "Poetry"],
  ["ECC", "Poetry"],
  ["SNG", "Poetry"],
  ["ISA", "Major Prophets"],
  ["JER", "Major Prophets"],
  ["LAM", "Major Prophets"],
  ["EZK", "Major Prophets"],
  ["DAN", "Major Prophets"],
  ["HOS", "Minor Prophets"],
  ["JOL", "Minor Prophets"],
  ["AMO", "Minor Prophets"],
  ["OBA", "Minor Prophets"],
  ["JON", "Minor Prophets"],
  ["MIC", "Minor Prophets"],
  ["NAM", "Minor Prophets"],
  ["HAB", "Minor Prophets"],
  ["ZEP", "Minor Prophets"],
  ["HAG", "Minor Prophets"],
  ["ZEC", "Minor Prophets"],
  ["MAL", "Minor Prophets"],
  ["MAT", "Gospels"],
  ["MRK", "Gospels"],
  ["LUK", "Gospels"],
  ["JHN", "Gospels"],
  ["ACT", "Early Church"],
  ["ROM", "Epistles"],
  ["1CO", "Epistles"],
  ["2CO", "Epistles"],
  ["GAL", "Epistles"],
  ["EPH", "Epistles"],
  ["PHP", "Epistles"],
  ["COL", "Epistles"],
  ["1TH", "Epistles"],
  ["2TH", "Epistles"],
  ["1TI", "Epistles"],
  ["2TI", "Epistles"],
  ["TIT", "Epistles"],
  ["PHM", "Epistles"],
  ["HEB", "Epistles"],
  ["JAS", "Epistles"],
  ["1PE", "Epistles"],
  ["2PE", "Epistles"],
  ["1JN", "Epistles"],
  ["2JN", "Epistles"],
  ["3JN", "Epistles"],
  ["JUD", "Epistles"],
  ["REV", "Prophetic"],
  ["TOB", "Apocrypha"],
  ["JDT", "Apocrypha"],
  ["WIS", "Apocrypha"],
  ["SIR", "Apocrypha"],
  ["BAR", "Apocrypha"],
  ["1MA", "Apocrypha"],
  ["2MA", "Apocrypha"],
  ["MAN", "Apocrypha"],
  ["1ES", "Apocrypha"],
  ["2ES", "Apocrypha"],
  ["PS2", "Apocrypha"],
  ["LAO", "Apocrypha"],
]);
