export const bookIdLookup = new Map([
  ["GEN", "Genesis"],
  ["EXO", "Exodus"],
  ["LEV", "Leviticus"],
  ["NUM", "Numbers"],
  ["DEU", "Deuteronomy"],
  ["JOS", "Joshua"],
  ["JDG", "Judges"],
  ["RUT", "Ruth"],
  ["1SA", "I Samuel"],
  ["2SA", "II Samuel"],
  ["1KI", "I Kings"],
  ["2KI", "II Kings"],
  ["1CH", "I Chronicles"],
  ["2CH", "II Chronicles"],
  ["EZR", "Ezra"],
  ["NEH", "Nehemiah"],
  ["EST", "Esther"],
  ["JOB", "Job"],
  ["PSA", "Psalms"],
  ["PRO", "Proverbs"],
  ["ECC", "Ecclesiastes"],
  ["SNG", "Song of Solomon"],
  ["ISA", "Isaiah"],
  ["JER", "Jeremiah"],
  ["LAM", "Lamentations"],
  ["EZK", "Ezekiel"],
  ["DAN", "Daniel"],
  ["HOS", "Hosea"],
  ["JOL", "Joel"],
  ["AMO", "Amos"],
  ["OBA", "Obadiah"],
  ["JON", "Jonah"],
  ["MIC", "Micah"],
  ["NAM", "Nahum"],
  ["HAB", "Habakkuk"],
  ["ZEP", "Zephaniah"],
  ["HAG", "Haggai"],
  ["ZEC", "Zechariah"],
  ["MAL", "Malachi"],
  ["MAT", "Matthew"],
  ["MRK", "Mark"],
  ["LUK", "Luke"],
  ["JHN", "John"],
  ["ACT", "Acts"],
  ["ROM", "Romans"],
  ["1CO", "I Corinthians"],
  ["2CO", "II Corinthians"],
  ["GAL", "Galatians"],
  ["EPH", "Ephesians"],
  ["PHP", "Philippians"],
  ["COL", "Colossians"],
  ["1TH", "I Thessalonians"],
  ["2TH", "II Thessalonians"],
  ["1TI", "I Timothy"],
  ["2TI", "II Timothy"],
  ["TIT", "Titus"],
  ["PHM", "Philemon"],
  ["HEB", "Hebrews"],
  ["JAS", "James"],
  ["1PE", "I Peter"],
  ["2PE", "II Peter"],
  ["1JN", "I John"],
  ["2JN", "II John"],
  ["3JN", "III John"],
  ["JUD", "Jude"],
  ["REV", "Revelation of John"],
  ["TOB", "Tobit"],
  ["JDT", "Judith"],
  ["WIS", "Wisdom"],
  ["SIR", "Sirach"],
  ["BAR", "Baruch"],
  ["1MA", "I Maccabees"],
  ["2MA", "II Maccabees"],
  ["MAN", "Prayer of Manasses"],
  ["1ES", "I Esdras"],
  ["2ES", "II Esdras"],
  ["PS2", "Additional Psalm"],
  ["LAO", "Laodiceans"],
]);

const bibleIdGroups = {
  Pentateuch: ["GEN", "EXO", "LEV", "NUM", "DEU"],
  History: [
    "JOS",
    "JDG",
    "RUT",
    "1SA",
    "2SA",
    "1KI",
    "2KI",
    "1CH",
    "2CH",
    "EZR",
    "NEH",
    "EST",
  ],
  Poetry: ["JOB", "PSA", "PRO", "ECC", "SNG"],
  "Major Prophets": ["ISA", "JER", "LAM", "EZK", "DAN"],
  "Minor Prophets": [
    "HOS",
    "JOL",
    "AMO",
    "OBA",
    "JON",
    "MIC",
    "NAM",
    "HAB",
    "ZEP",
    "HAG",
    "ZEC",
    "MAL",
  ],
  Gospels: ["MAT", "MRK", "LUK", "JHN"],
  "Early Church": ["ACT"],
  Epistles: [
    "ROM",
    "1CO",
    "2CO",
    "GAL",
    "EPH",
    "PHP",
    "COL",
    "1TH",
    "2TH",
    "1TI",
    "2TI",
    "TIT",
    "PHM",
    "HEB",
    "JAS",
    "1PE",
    "2PE",
    "1JN",
    "2JN",
    "3JN",
    "JUD",
  ],
  Prophetic: ["REV"],
};
